"""Seed the Career Vision catalog: 27 courses + 20 partner colleges.

Run:  cd /app/backend && python seed.py
Idempotent — wipes and repopulates `courses` / `colleges`, then rebuilds indexes.
"""

import asyncio

from lib.db import db, ensure_indexes
from models.catalog import College, Course

COURSES: list[dict] = [
    # Engineering & Technology
    dict(id="course-btech", name="B.Tech (Bachelor of Technology)", category="Engineering & Technology", level="Undergraduate", duration="4 Years", eligibility="10+2 with Physics, Chemistry, Maths (PCM) — min 45%", fee_range="₹3 – 6 Lakh (total)", description="Industry-aligned engineering degrees across CSE, Mechanical, Civil, Electrical, AI & Data Science branches with internship-linked curricula.", career_outcomes=["Software Engineer", "Core Branch Engineer", "M.Tech / GATE", "PSU & Private Jobs"], popular=True),
    dict(id="course-mtech", name="M.Tech (Master of Technology)", category="Engineering & Technology", level="Postgraduate", duration="2 Years", eligibility="B.Tech / BE in a relevant branch", fee_range="₹1 – 2.5 Lakh (total)", description="Specialisation-level engineering qualification for research, academia and senior technical roles.", career_outcomes=["Senior Engineer", "R&D Roles", "Assistant Professor"], popular=False),
    dict(id="course-barch", name="B.Arch (Bachelor of Architecture)", category="Engineering & Technology", level="Undergraduate", duration="5 Years", eligibility="10+2 PCM with NATA / JEE Main Paper-2", fee_range="₹2.5 – 5 Lakh (total)", description="Professional architecture degree combining design studios, construction technology and practical training.", career_outcomes=["Architect", "Urban Planner", "Design Consultant"], popular=False),
    dict(id="course-polytechnic", name="Diploma in Engineering (Polytechnic)", category="Engineering & Technology", level="Diploma", duration="3 Years", eligibility="10th pass from any recognised board", fee_range="₹0.6 – 1.5 Lakh (total)", description="Job-oriented technical diploma with direct lateral-entry pathway into the 2nd year of B.Tech.", career_outcomes=["Junior Engineer", "Lateral Entry to B.Tech", "Supervisor Roles"], popular=False),
    # Computer Applications
    dict(id="course-bca", name="BCA (Bachelor of Computer Applications)", category="Computer Applications", level="Undergraduate", duration="3 Years", eligibility="10+2 any stream (Maths / Computer preferred)", fee_range="₹1.5 – 3 Lakh (total)", description="Hands-on computing degree covering programming, databases, cloud and modern application development.", career_outcomes=["Software Developer", "Web Developer", "MCA", "IT Support & QA"], popular=True),
    dict(id="course-mca", name="MCA (Master of Computer Applications)", category="Computer Applications", level="Postgraduate", duration="2 Years", eligibility="BCA / B.Sc CS or graduation with Mathematics", fee_range="₹1.2 – 2.8 Lakh (total)", description="Advanced computing masters with specialisations in AI-ML, full-stack development and data engineering.", career_outcomes=["Software Engineer", "Data Analyst", "System Architect"], popular=False),
    dict(id="course-bsc-cs", name="B.Sc Computer Science", category="Computer Applications", level="Undergraduate", duration="3 Years", eligibility="10+2 with Maths / Computer Science", fee_range="₹1 – 2.2 Lakh (total)", description="Science-anchored computing degree strong in algorithms, mathematics and systems fundamentals.", career_outcomes=["IT Analyst", "Developer", "M.Sc / MCA"], popular=False),
    # Management & Commerce
    dict(id="course-bba", name="BBA (Bachelor of Business Administration)", category="Management & Commerce", level="Undergraduate", duration="3 Years", eligibility="10+2 any stream — min 45%", fee_range="₹1.5 – 3.5 Lakh (total)", description="Foundational management degree with specialisations in marketing, finance, HR and business analytics.", career_outcomes=["Management Trainee", "MBA", "Entrepreneurship"], popular=True),
    dict(id="course-mba", name="MBA (Master of Business Administration)", category="Management & Commerce", level="Postgraduate", duration="2 Years", eligibility="Graduation any stream (CAT / MAT / CMAT accepted)", fee_range="₹2 – 8 Lakh (total)", description="Flagship management qualification with placements across banking, consulting, FMCG and tech companies.", career_outcomes=["Manager", "Business Analyst", "HR / Marketing Leadership"], popular=True),
    dict(id="course-bcom", name="B.Com (Hons)", category="Management & Commerce", level="Undergraduate", duration="3 Years", eligibility="10+2 Commerce — min 45%", fee_range="₹0.8 – 1.8 Lakh (total)", description="Commerce honours degree covering accounting, taxation, auditing and financial management.", career_outcomes=["Accountant", "CA / CS Preparation", "Banking & Finance"], popular=False),
    dict(id="course-pgdm", name="PGDM (Post Graduate Diploma in Management)", category="Management & Commerce", level="Postgraduate", duration="2 Years", eligibility="Graduation + entrance score", fee_range="₹3 – 7 Lakh (total)", description="AICTE-approved autonomous management programme with strong corporate interface and internships.", career_outcomes=["Consulting Roles", "Operations Manager", "Financial Analyst"], popular=False),
    # Medical & Nursing
    dict(id="course-bsc-nursing", name="B.Sc Nursing", category="Medical & Nursing", level="Undergraduate", duration="4 Years", eligibility="10+2 with PCB (Physics, Chemistry, Biology) — min 45%", fee_range="₹2 – 5 Lakh (total)", description="Clinical nursing degree with hospital rotations, registered-nurse licensing pathway and overseas mobility.", career_outcomes=["Staff Nurse (Govt/Private)", "Abroad Placements", "M.Sc Nursing"], popular=True),
    dict(id="course-gnm", name="GNM (General Nursing & Midwifery)", category="Medical & Nursing", level="Diploma", duration="3 Years + 6 Months Internship", eligibility="10+2 any stream (PCB preferred)", fee_range="₹1.2 – 2.5 Lakh (total)", description="Diploma in general nursing and midwifery with intensive hospital-based clinical training.", career_outcomes=["Registered Nurse", "Hospital Nursing Roles", "Community Health"], popular=False),
    dict(id="course-anm", name="ANM (Auxiliary Nursing & Midwifery)", category="Medical & Nursing", level="Diploma", duration="2 Years", eligibility="10+2 any stream — min 40%", fee_range="₹0.8 – 1.6 Lakh (total)", description="Entry-level nursing diploma focused on maternal and community health services.", career_outcomes=["Auxiliary Nurse", "Health Worker (Govt)", "Clinic Roles"], popular=False),
    dict(id="course-bpt", name="BPT (Bachelor of Physiotherapy)", category="Medical & Nursing", level="Undergraduate", duration="4.5 Years", eligibility="10+2 with PCB", fee_range="₹2 – 4 Lakh (total)", description="Rehabilitation-science degree with clinical postings in ortho, neuro and sports physiotherapy.", career_outcomes=["Physiotherapist", "Sports Rehab", "Own Clinic"], popular=False),
    dict(id="course-bams", name="BAMS (Bachelor of Ayurvedic Medicine & Surgery)", category="Medical & Nursing", level="Undergraduate", duration="5.5 Years", eligibility="10+2 PCB with NEET qualification", fee_range="₹2 – 6 Lakh (total)", description="AYUSH-recognised ayurvedic medicine degree with internship and doctor registration pathway.", career_outcomes=["Ayurvedic Doctor", "Wellness Industry", "Govt AYUSH Dispensaries"], popular=False),
    # Pharmacy
    dict(id="course-bpharma", name="B.Pharma (Bachelor of Pharmacy)", category="Pharmacy", level="Undergraduate", duration="4 Years", eligibility="10+2 with PCB / PCM", fee_range="₹1.5 – 4 Lakh (total)", description="Pharmaceutical science degree with lab practice, drug regulation studies and industry internships.", career_outcomes=["Pharmacist", "Pharma Companies", "Drug Inspector Prep"], popular=True),
    dict(id="course-dpharma", name="D.Pharma (Diploma in Pharmacy)", category="Pharmacy", level="Diploma", duration="2 Years", eligibility="10+2 with PCB / PCM", fee_range="₹0.8 – 1.8 Lakh (total)", description="Quick-entry pharmacy diploma leading to registration as a licensed pharmacist.", career_outcomes=["Registered Pharmacist", "Medical Store", "Lateral B.Pharma"], popular=False),
    dict(id="course-mpharma", name="M.Pharma (Master of Pharmacy)", category="Pharmacy", level="Postgraduate", duration="2 Years", eligibility="B.Pharma with GPAT score", fee_range="₹1.5 – 3 Lakh (total)", description="Postgraduate pharmacy specialisation across pharmaceutics, pharmacology and quality assurance.", career_outcomes=["Pharma R&D", "Regulatory Affairs", "Teaching"], popular=False),
    # Law
    dict(id="course-ba-llb", name="BA LL.B (Integrated Law)", category="Law", level="Undergraduate", duration="5 Years", eligibility="10+2 any stream — min 45% (CLAT preferred)", fee_range="₹2 – 5 Lakh (total)", description="Integrated arts-and-law honours programme with moot courts, internships and bar-council recognition.", career_outcomes=["Advocate", "Judicial Services", "Corporate Counsel"], popular=True),
    dict(id="course-llb", name="LL.B (Bachelor of Laws)", category="Law", level="Undergraduate", duration="3 Years", eligibility="Graduation in any stream", fee_range="₹1.2 – 3 Lakh (total)", description="Classic three-year law degree for graduates entering litigation or corporate legal practice.", career_outcomes=["Advocate", "Legal Advisor", "Company Secretary Prep"], popular=False),
    # Education
    dict(id="course-bed", name="B.Ed (Bachelor of Education)", category="Education", level="Undergraduate", duration="2 Years", eligibility="Graduation with min 50%", fee_range="₹0.6 – 1.5 Lakh (total)", description="NCTE-recognised teacher-training degree with teaching practice in schools.", career_outcomes=["TGT / PGT Teacher", "CTET / TET Prep", "Edu-trainer"], popular=False),
    dict(id="course-deled", name="D.El.Ed (Diploma in Elementary Education)", category="Education", level="Diploma", duration="2 Years", eligibility="10+2 with min 50%", fee_range="₹0.5 – 1.2 Lakh (total)", description="Elementary teacher preparation diploma for primary-school teaching careers.", career_outcomes=["Primary Teacher", "Govt Teacher Exams"], popular=False),
    # Agriculture
    dict(id="course-bsc-agri", name="B.Sc Agriculture", category="Agriculture", level="Undergraduate", duration="4 Years", eligibility="10+2 with PCB / PCM / Agriculture", fee_range="₹1.2 – 2.8 Lakh (total)", description="Applied agriculture science degree covering agronomy, soil science, horticulture and agri-business.", career_outcomes=["Agriculture Officer", "IBPS SO (Agri)", "Agri-business"], popular=True),
    dict(id="course-bsc-horti", name="B.Sc Horticulture", category="Agriculture", level="Undergraduate", duration="4 Years", eligibility="10+2 with PCB / PCM / Agriculture", fee_range="₹1 – 2.2 Lakh (total)", description="Specialised degree in fruit, vegetable, flower and plantation crop production technology.", career_outcomes=["Horticulture Officer", "Landscape Industry", "Agri-startups"], popular=False),
    # Arts & Media
    dict(id="course-ba-psychology", name="BA (Hons) Psychology", category="Arts & Media", level="Undergraduate", duration="3 Years", eligibility="10+2 any stream", fee_range="₹0.9 – 2 Lakh (total)", description="Psychology honours degree with labs, testing practice and counselling exposure.", career_outcomes=["Counsellor", "HR Roles", "MA Psychology"], popular=False),
    dict(id="course-bjmc", name="BJMC (Journalism & Mass Communication)", category="Arts & Media", level="Undergraduate", duration="3 Years", eligibility="10+2 any stream", fee_range="₹1 – 2.2 Lakh (total)", description="Media degree spanning reporting, broadcast production, PR and digital content.", career_outcomes=["Journalist", "PR Executive", "Content & Social Media"], popular=False),
    dict(id="course-bhm", name="BHM (Bachelor of Hotel Management)", category="Arts & Media", level="Undergraduate", duration="4 Years", eligibility="10+2 any stream", fee_range="₹2 – 4 Lakh (total)", description="Hospitality management degree with kitchen labs, front-office training and hotel internships.", career_outcomes=["Hotels & Resorts", "Airlines & Cruise", "Event Management"], popular=False),
]

COLLEGES: list[dict] = [
    dict(id="col-galgotias", name="Galgotias University", city="Greater Noida", state="Uttar Pradesh", type="Private", streams=["Engineering & Technology", "Computer Applications", "Management & Commerce", "Law"], rating=4.3, fee_range="₹1.6 – 3.2 Lakh / year", description="NAAC A+ campus near Delhi with strong placement support across engineering, management and law programmes.", featured=True),
    dict(id="col-amity-noida", name="Amity University", city="Noida", state="Uttar Pradesh", type="Private", streams=["Engineering & Technology", "Management & Commerce", "Law", "Paramedical & Health"], rating=4.5, fee_range="₹2.8 – 4.5 Lakh / year", description="One of India's most recognised private universities with 400+ programmes and a global alumni network.", featured=True),
    dict(id="col-sharda", name="Sharda University", city="Greater Noida", state="Uttar Pradesh", type="Private", streams=["Engineering & Technology", "Management & Commerce", "Medical & Nursing", "Computer Applications"], rating=4.2, fee_range="₹1.8 – 3.6 Lakh / year", description="Multi-disciplinary university with 270+ programmes, an on-campus hospital and students from 95+ countries.", featured=True),
    dict(id="col-srm-sonepat", name="SRM University Delhi-NCR", city="Sonepat", state="Haryana", type="Private", streams=["Engineering & Technology", "Computer Applications", "Management & Commerce", "Pharmacy"], rating=4.3, fee_range="₹2 – 3.5 Lakh / year", description="SRM's Delhi-NCR campus with modern labs, industry tie-ups and a dedicated placement cell.", featured=True),
    dict(id="col-lpu", name="Lovely Professional University", city="Phagwara", state="Punjab", type="Private", streams=["Engineering & Technology", "Management & Commerce", "Computer Applications", "Arts & Media"], rating=4.4, fee_range="₹1.2 – 3.2 Lakh / year", description="India's largest private university with 600+ programmes, top-class sports facilities and massive placement drives.", featured=True),
    dict(id="col-cu-mohali", name="Chandigarh University", city="Mohali", state="Punjab", type="Private", streams=["Engineering & Technology", "Computer Applications", "Management & Commerce", "Pharmacy"], rating=4.4, fee_range="₹1.5 – 3 Lakh / year", description="NAAC A+ university known for engineering excellence, record recruitment numbers and innovation labs.", featured=True),
    dict(id="col-upes", name="UPES Dehradun", city="Dehradun", state="Uttarakhand", type="Private", streams=["Engineering & Technology", "Management & Commerce", "Law", "Computer Applications"], rating=4.3, fee_range="₹2.5 – 4.5 Lakh / year", description="Domain-focused university with specialised programmes in energy, design, law and applied engineering.", featured=False),
    dict(id="col-graphic-era", name="Graphic Era University", city="Dehradun", state="Uttarakhand", type="Private (Deemed)", streams=["Engineering & Technology", "Computer Applications", "Management & Commerce", "Paramedical & Health"], rating=4.2, fee_range="₹1.4 – 2.8 Lakh / year", description="Deemed university with consistent placement records and strong computer science departments.", featured=False),
    dict(id="col-manipal-jaipur", name="Manipal University Jaipur", city="Jaipur", state="Rajasthan", type="Private", streams=["Engineering & Technology", "Computer Applications", "Management & Commerce", "Arts & Media"], rating=4.4, fee_range="₹2 – 4 Lakh / year", description="Modern Manipal campus with emerging-tech programmes, creative studios and strong industry mentorship.", featured=False),
    dict(id="col-sgt", name="SGT University", city="Gurugram", state="Haryana", type="Private", streams=["Medical & Nursing", "Pharmacy", "Paramedical & Health", "Law"], rating=4.1, fee_range="₹1.8 – 4 Lakh / year", description="Health-sciences focused university with a teaching hospital, nursing labs and pharmacy practice wings.", featured=False),
    dict(id="col-christ", name="Christ University", city="Bengaluru", state="Karnataka", type="Private (Deemed)", streams=["Management & Commerce", "Law", "Arts & Media", "Computer Applications"], rating=4.6, fee_range="₹1.8 – 3.5 Lakh / year", description="Premier deemed university celebrated for academic rigour, discipline and holistic campus life.", featured=False),
    dict(id="col-jain", name="Jain University", city="Bengaluru", state="Karnataka", type="Private (Deemed)", streams=["Management & Commerce", "Computer Applications", "Engineering & Technology", "Arts & Media"], rating=4.3, fee_range="₹2 – 4 Lakh / year", description="Deemed-to-be university with an entrepreneurial culture, sports scholars and industry-curated programmes.", featured=False),
    dict(id="col-parul", name="Parul University", city="Vadodara", state="Gujarat", type="Private", streams=["Engineering & Technology", "Medical & Nursing", "Pharmacy", "Management & Commerce"], rating=4.2, fee_range="₹1 – 2.4 Lakh / year", description="Fast-growing multi-faculty university with 250+ programmes and students from 60+ countries.", featured=False),
    dict(id="col-sandip", name="Sandip University", city="Nashik", state="Maharashtra", type="Private", streams=["Engineering & Technology", "Computer Applications", "Law", "Education"], rating=4.0, fee_range="₹1 – 2.2 Lakh / year", description="250-acre campus university offering affordable professional programmes with hands-on industry training.", featured=False),
    dict(id="col-shobhit", name="Shobhit University", city="Meerut", state="Uttar Pradesh", type="Private (Deemed)", streams=["Agriculture", "Pharmacy", "Computer Applications", "Education"], rating=4.0, fee_range="₹0.9 – 2 Lakh / year", description="Deemed university with recognised regular programmes across agriculture, pharmacy and education.", featured=False),
    dict(id="col-mangalayatan", name="Mangalayatan University", city="Aligarh", state="Uttar Pradesh", type="Private", streams=["Engineering & Technology", "Management & Commerce", "Law", "Education"], rating=3.9, fee_range="₹0.9 – 2 Lakh / year", description="Peaceful residential campus with professional courses, hostel facilities and scholarship options.", featured=False),
    dict(id="col-niu", name="Noida International University", city="Greater Noida", state="Uttar Pradesh", type="Private", streams=["Engineering & Technology", "Law", "Management & Commerce", "Medical & Nursing"], rating=3.9, fee_range="₹1 – 2.2 Lakh / year", description="UGC-recognised university in the Delhi-NCR education hub with moot courts and simulation labs.", featured=False),
    dict(id="col-tmu", name="Teerthanker Mahaveer University", city="Moradabad", state="Uttar Pradesh", type="Private", streams=["Medical & Nursing", "Paramedical & Health", "Engineering & Technology", "Education"], rating=4.0, fee_range="₹1 – 2.3 Lakh / year", description="Known for nursing, paramedical and teacher-education programmes with hospital-linked training.", featured=False),
    dict(id="col-amity-patna", name="Amity University Patna", city="Patna", state="Bihar", type="Private", streams=["Management & Commerce", "Computer Applications", "Law", "Arts & Media"], rating=4.0, fee_range="₹1.2 – 2.5 Lakh / year", description="Amity's Bihar campus bringing the group's academic standards closer to home for Bihar students.", featured=False),
    dict(id="col-patna-univ", name="Patna University", city="Patna", state="Bihar", type="Government", streams=["Management & Commerce", "Law", "Arts & Media", "Education"], rating=4.0, fee_range="₹0.3 – 0.8 Lakh / year", description="One of India's oldest universities (est. 1917) offering highly affordable, recognised degree programmes.", featured=False),
    # ── Owner-supplied partner list ──────────────────────────────────────────
    dict(id="col-bits-pilani", name="BITS Pilani", city="Pilani", state="Rajasthan", type="Private (Deemed)", streams=["Engineering & Technology", "Computer Applications", "Pharmacy", "Management & Commerce"], rating=4.8, fee_range="₹5 – 6.5 Lakh / year", description="India's most prestigious private engineering institute, admission through BITSAT, with outstanding placement records.", featured=True),
    dict(id="col-mahe-manipal", name="Manipal Academy of Higher Education (MAHE)", city="Manipal", state="Karnataka", type="Private (Deemed)", streams=["Medical & Nursing", "Engineering & Technology", "Pharmacy", "Management & Commerce"], rating=4.7, fee_range="₹4 – 8 Lakh / year", description="Institution of Eminence renowned for medicine, nursing, engineering and allied health sciences.", featured=True),
    dict(id="col-vit-vellore", name="VIT Vellore", city="Vellore", state="Tamil Nadu", type="Private (Deemed)", streams=["Engineering & Technology", "Computer Applications", "Management & Commerce", "Law"], rating=4.6, fee_range="₹2 – 4.5 Lakh / year", description="Top-ranked private engineering university, admission via VITEEE, with very strong campus recruitment.", featured=True),
    dict(id="col-srm-chennai", name="SRM Institute of Science & Technology", city="Chennai", state="Tamil Nadu", type="Private (Deemed)", streams=["Engineering & Technology", "Medical & Nursing", "Management & Commerce", "Law"], rating=4.5, fee_range="₹2.5 – 5 Lakh / year", description="Flagship SRM campus at Kattankulathur with world-class labs and large multinational recruitment drives.", featured=True),
    dict(id="col-shiv-nadar", name="Shiv Nadar University", city="Greater Noida", state="Uttar Pradesh", type="Private", streams=["Engineering & Technology", "Arts & Media", "Management & Commerce", "Computer Applications"], rating=4.5, fee_range="₹4 – 6 Lakh / year", description="Research-intensive liberal-tech university with small class sizes and generous merit scholarships.", featured=False),
    dict(id="col-op-jindal", name="O.P. Jindal Global University", city="Sonipat", state="Haryana", type="Private", streams=["Law", "Management & Commerce", "Arts & Media"], rating=4.6, fee_range="₹5 – 8 Lakh / year", description="India's leading private law university (JGLS), globally ranked, with international faculty and exchange programmes.", featured=True),
    dict(id="col-ashoka", name="Ashoka University", city="Sonipat", state="Haryana", type="Private", streams=["Arts & Media", "Management & Commerce", "Computer Applications"], rating=4.6, fee_range="₹7 – 10 Lakh / year", description="India's premier liberal-arts university with need-blind admission and substantial financial aid.", featured=False),
    dict(id="col-amrita", name="Amrita Vishwa Vidyapeetham", city="Coimbatore", state="Tamil Nadu", type="Private (Deemed)", streams=["Engineering & Technology", "Medical & Nursing", "Pharmacy", "Management & Commerce"], rating=4.5, fee_range="₹2.5 – 5 Lakh / year", description="NAAC A++ multi-campus university strong across engineering, medicine and allied health sciences.", featured=False),
    dict(id="col-thapar", name="Thapar Institute of Engineering & Technology", city="Patiala", state="Punjab", type="Private (Deemed)", streams=["Engineering & Technology", "Computer Applications", "Management & Commerce"], rating=4.5, fee_range="₹3.5 – 4.5 Lakh / year", description="Long-established engineering institute with excellent core-branch teaching and placement support.", featured=False),
    dict(id="col-symbiosis", name="Symbiosis International University", city="Pune", state="Maharashtra", type="Private (Deemed)", streams=["Management & Commerce", "Law", "Computer Applications", "Arts & Media"], rating=4.6, fee_range="₹3.5 – 7 Lakh / year", description="Renowned for management and law programmes, admission via SET/SNAP, with strong corporate placements.", featured=True),
    dict(id="col-kiit", name="KIIT University", city="Bhubaneswar", state="Odisha", type="Private (Deemed)", streams=["Engineering & Technology", "Medical & Nursing", "Management & Commerce", "Law"], rating=4.4, fee_range="₹2 – 4 Lakh / year", description="Large modern campus with KIITEE-based admission and consistently high recruiter participation.", featured=False),
    dict(id="col-chitkara", name="Chitkara University", city="Rajpura", state="Punjab", type="Private", streams=["Engineering & Technology", "Computer Applications", "Management & Commerce", "Paramedical & Health"], rating=4.3, fee_range="₹1.8 – 3.2 Lakh / year", description="Industry-partnered university known for placement-focused engineering and healthcare programmes.", featured=False),
    dict(id="col-shoolini", name="Shoolini University", city="Solan", state="Himachal Pradesh", type="Private", streams=["Pharmacy", "Engineering & Technology", "Management & Commerce", "Agriculture"], rating=4.2, fee_range="₹1.8 – 3.5 Lakh / year", description="Research-ranked private university in the Himalayan foothills, strong in pharmacy and biotechnology.", featured=False),
    dict(id="col-nmims", name="NMIMS", city="Mumbai", state="Maharashtra", type="Private (Deemed)", streams=["Management & Commerce", "Engineering & Technology", "Pharmacy", "Law"], rating=4.5, fee_range="₹3 – 7 Lakh / year", description="Top Mumbai deemed university, especially respected for its business school and pharmacy faculty.", featured=False),
    dict(id="col-alliance", name="Alliance University", city="Bengaluru", state="Karnataka", type="Private", streams=["Management & Commerce", "Engineering & Technology", "Law", "Arts & Media"], rating=4.2, fee_range="₹2.5 – 5 Lakh / year", description="Bengaluru business-focused university with AACSB-track management programmes and corporate mentoring.", featured=False),
    dict(id="col-bennett", name="Bennett University", city="Greater Noida", state="Uttar Pradesh", type="Private", streams=["Engineering & Technology", "Computer Applications", "Management & Commerce", "Law"], rating=4.4, fee_range="₹3.5 – 5 Lakh / year", description="Times Group university with modern CS specialisations, strong faculty and industry-linked projects.", featured=False),
    dict(id="col-niit-univ", name="NIIT University", city="Neemrana", state="Rajasthan", type="Private", streams=["Computer Applications", "Engineering & Technology", "Management & Commerce"], rating=4.2, fee_range="₹3 – 4.5 Lakh / year", description="Industry-linked technology university with mandatory internships built into every programme.", featured=False),
    dict(id="col-sastra", name="SASTRA Deemed University", city="Thanjavur", state="Tamil Nadu", type="Private (Deemed)", streams=["Engineering & Technology", "Management & Commerce", "Law", "Computer Applications"], rating=4.3, fee_range="₹1.5 – 3 Lakh / year", description="Affordable, academically rigorous deemed university with excellent core engineering outcomes.", featured=False),
    dict(id="col-kalinga", name="Kalinga University", city="Raipur", state="Chhattisgarh", type="Private", streams=["Engineering & Technology", "Management & Commerce", "Computer Applications", "Education"], rating=3.9, fee_range="₹0.8 – 1.8 Lakh / year", description="Budget-friendly private university in central India with a wide range of professional programmes.", featured=False),
    dict(id="col-manav-rachna", name="Manav Rachna International Institute", city="Faridabad", state="Haryana", type="Private (Deemed)", streams=["Engineering & Technology", "Computer Applications", "Management & Commerce", "Paramedical & Health"], rating=4.1, fee_range="₹1.8 – 3.5 Lakh / year", description="Delhi-NCR deemed institute with strong industry tie-ups and sports-scholarship opportunities.", featured=False),
    dict(id="col-bml-munjal", name="BML Munjal University", city="Gurugram", state="Haryana", type="Private", streams=["Engineering & Technology", "Management & Commerce", "Law", "Computer Applications"], rating=4.2, fee_range="₹3 – 4.5 Lakh / year", description="Hero Group university with an Imperial College academic partnership and small-batch teaching.", featured=False),
    dict(id="col-pes", name="PES University", city="Bengaluru", state="Karnataka", type="Private", streams=["Engineering & Technology", "Computer Applications", "Management & Commerce"], rating=4.4, fee_range="₹3.5 – 5 Lakh / year", description="Highly regarded Bengaluru engineering university with excellent CS placements in product companies.", featured=False),
    dict(id="col-reva", name="REVA University", city="Bengaluru", state="Karnataka", type="Private", streams=["Engineering & Technology", "Computer Applications", "Management & Commerce", "Law"], rating=4.1, fee_range="₹2 – 3.5 Lakh / year", description="Large green campus in north Bengaluru offering a broad spread of professional degrees.", featured=False),
    dict(id="col-presidency-blr", name="Presidency University", city="Bengaluru", state="Karnataka", type="Private", streams=["Engineering & Technology", "Management & Commerce", "Computer Applications", "Law"], rating=4.0, fee_range="₹2 – 3.5 Lakh / year", description="Bengaluru university with industry-aligned curricula and an active placement cell.", featured=False),
    dict(id="col-jaypee-juit", name="Jaypee University of Information Technology", city="Waknaghat", state="Himachal Pradesh", type="Private", streams=["Engineering & Technology", "Computer Applications"], rating=4.2, fee_range="₹2 – 3.2 Lakh / year", description="Focused IT and engineering university on a scenic hill campus with solid core-CS teaching.", featured=False),
    dict(id="col-geu-hill", name="Graphic Era Hill University", city="Dehradun", state="Uttarakhand", type="Private", streams=["Engineering & Technology", "Computer Applications", "Management & Commerce", "Paramedical & Health"], rating=4.0, fee_range="₹1.2 – 2.4 Lakh / year", description="Graphic Era's hill-state university with affordable professional programmes across Uttarakhand campuses.", featured=False),
    dict(id="col-quantum", name="Quantum University", city="Roorkee", state="Uttarakhand", type="Private", streams=["Engineering & Technology", "Computer Applications", "Management & Commerce", "Paramedical & Health"], rating=3.9, fee_range="₹1 – 2.2 Lakh / year", description="Skill-first university near Roorkee with practical training and placement assistance.", featured=False),
    dict(id="col-tulas", name="Tula's Institute", city="Dehradun", state="Uttarakhand", type="Private", streams=["Engineering & Technology", "Computer Applications", "Management & Commerce"], rating=3.9, fee_range="₹1 – 2 Lakh / year", description="Dehradun institute known for disciplined campus life, hostels and placement-oriented training.", featured=False),
    dict(id="col-ims-unison", name="IMS Unison University", city="Dehradun", state="Uttarakhand", type="Private", streams=["Management & Commerce", "Law", "Arts & Media", "Computer Applications"], rating=4.0, fee_range="₹1.2 – 2.6 Lakh / year", description="Established Dehradun university respected for management, law and mass-communication programmes.", featured=False),
    dict(id="col-kr-mangalam", name="K.R. Mangalam University", city="Gurugram", state="Haryana", type="Private", streams=["Engineering & Technology", "Management & Commerce", "Law", "Paramedical & Health"], rating=4.0, fee_range="₹1.8 – 3.2 Lakh / year", description="Gurugram university with a wide programme mix and growing recruiter base in Delhi-NCR.", featured=False),
    dict(id="col-geeta", name="Geeta University", city="Panipat", state="Haryana", type="Private", streams=["Engineering & Technology", "Computer Applications", "Management & Commerce", "Pharmacy"], rating=3.9, fee_range="₹1 – 2.2 Lakh / year", description="Affordable Haryana university offering engineering, pharmacy and management with hostel facilities.", featured=False),
    dict(id="col-mmu", name="Maharishi Markandeshwar University", city="Ambala", state="Haryana", type="Private (Deemed)", streams=["Medical & Nursing", "Paramedical & Health", "Pharmacy", "Engineering & Technology"], rating=4.1, fee_range="₹1.5 – 4 Lakh / year", description="Health-sciences deemed university with its own medical college, dental wing and teaching hospital.", featured=False),
    dict(id="col-jecrc", name="JECRC University", city="Jaipur", state="Rajasthan", type="Private", streams=["Engineering & Technology", "Computer Applications", "Management & Commerce", "Law"], rating=4.1, fee_range="₹1.5 – 3 Lakh / year", description="Jaipur university with a strong startup-and-innovation culture and active placement drives.", featured=False),
    dict(id="col-poornima", name="Poornima University", city="Jaipur", state="Rajasthan", type="Private", streams=["Engineering & Technology", "Computer Applications", "Management & Commerce", "Arts & Media"], rating=4.0, fee_range="₹1.2 – 2.6 Lakh / year", description="Jaipur institution focused on employability training, design and applied engineering.", featured=False),
    dict(id="col-mody", name="Mody University", city="Lakshmangarh", state="Rajasthan", type="Private", streams=["Engineering & Technology", "Computer Applications", "Management & Commerce", "Pharmacy"], rating=4.0, fee_range="₹1.5 – 3 Lakh / year", description="Residential university with a dedicated girls' campus, strong safety and mentoring culture.", featured=False),
    dict(id="col-ganpat", name="Ganpat University", city="Mehsana", state="Gujarat", type="Private", streams=["Engineering & Technology", "Pharmacy", "Management & Commerce", "Computer Applications"], rating=4.1, fee_range="₹1.2 – 2.8 Lakh / year", description="Gujarat university with respected pharmacy and engineering faculties and industry internships.", featured=False),
    dict(id="col-pp-savani", name="P.P. Savani University", city="Surat", state="Gujarat", type="Private", streams=["Engineering & Technology", "Computer Applications", "Management & Commerce", "Paramedical & Health"], rating=3.9, fee_range="₹1 – 2.4 Lakh / year", description="Modern Surat campus offering engineering, health sciences and management programmes.", featured=False),
    dict(id="col-gnsu", name="Gopal Narayan Singh University", city="Sasaram", state="Bihar", type="Private", streams=["Medical & Nursing", "Paramedical & Health", "Pharmacy", "Engineering & Technology"], rating=4.0, fee_range="₹1.2 – 4 Lakh / year", description="Bihar's well-known private health-sciences university with nursing, pharmacy and medical programmes close to home.", featured=True),
]


async def main() -> None:
    for collection, rows in (("courses", COURSES), ("colleges", COLLEGES)):
        model = Course if collection == "courses" else College
        docs = [model(**row).model_dump() for row in rows]
        await db[collection].delete_many({})
        await db[collection].insert_many(docs)
        print(f"seeded {len(docs)} {collection}")
    await ensure_indexes()
    print("indexes ensured")


if __name__ == "__main__":
    asyncio.run(main())
