// Small fallback datasets used ONLY when the backend is unreachable, so directory
// grids degrade to a partial page instead of an outage (see TEMPLATE.md §4).
import type { College, Course } from "@/lib/types";

export const FALLBACK_COURSES: Course[] = [
  {
    id: "course-btech",
    name: "B.Tech (Bachelor of Technology)",
    category: "Engineering & Technology",
    level: "Undergraduate",
    duration: "4 Years",
    eligibility: "10+2 with Physics, Chemistry, Maths (PCM) — min 45%",
    fee_range: "₹3 – 6 Lakh (total)",
    description:
      "Industry-aligned engineering degrees across CSE, Mechanical, Civil, Electrical, AI & Data Science branches.",
    career_outcomes: ["Software Engineer", "Core Branch Engineer", "M.Tech / GATE", "PSU & Private Jobs"],
    popular: true,
  },
  {
    id: "course-bca",
    name: "BCA (Bachelor of Computer Applications)",
    category: "Computer Applications",
    level: "Undergraduate",
    duration: "3 Years",
    eligibility: "10+2 any stream (Maths / Computer preferred)",
    fee_range: "₹1.5 – 3 Lakh (total)",
    description: "Hands-on computing degree covering programming, databases, cloud and modern application development.",
    career_outcomes: ["Software Developer", "Web Developer", "MCA", "IT Support & QA"],
    popular: true,
  },
  {
    id: "course-bba",
    name: "BBA (Bachelor of Business Administration)",
    category: "Management & Commerce",
    level: "Undergraduate",
    duration: "3 Years",
    eligibility: "10+2 any stream — min 45%",
    fee_range: "₹1.5 – 3.5 Lakh (total)",
    description: "Foundational management degree with specialisations in marketing, finance, HR and business analytics.",
    career_outcomes: ["Management Trainee", "MBA", "Entrepreneurship"],
    popular: true,
  },
  {
    id: "course-mba",
    name: "MBA (Master of Business Administration)",
    category: "Management & Commerce",
    level: "Postgraduate",
    duration: "2 Years",
    eligibility: "Graduation any stream (CAT / MAT / CMAT accepted)",
    fee_range: "₹2 – 8 Lakh (total)",
    description: "Flagship management qualification with placements across banking, consulting, FMCG and tech companies.",
    career_outcomes: ["Manager", "Business Analyst", "HR / Marketing Leadership"],
    popular: true,
  },
  {
    id: "course-bsc-nursing",
    name: "B.Sc Nursing",
    category: "Medical & Nursing",
    level: "Undergraduate",
    duration: "4 Years",
    eligibility: "10+2 with PCB (Physics, Chemistry, Biology) — min 45%",
    fee_range: "₹2 – 5 Lakh (total)",
    description: "Clinical nursing degree with hospital rotations, registered-nurse licensing pathway and overseas mobility.",
    career_outcomes: ["Staff Nurse (Govt/Private)", "Abroad Placements", "M.Sc Nursing"],
    popular: true,
  },
  {
    id: "course-bpharma",
    name: "B.Pharma (Bachelor of Pharmacy)",
    category: "Pharmacy",
    level: "Undergraduate",
    duration: "4 Years",
    eligibility: "10+2 with PCB / PCM",
    fee_range: "₹1.5 – 4 Lakh (total)",
    description: "Pharmaceutical science degree with lab practice, drug regulation studies and industry internships.",
    career_outcomes: ["Pharmacist", "Pharma Companies", "Drug Inspector Prep"],
    popular: true,
  },
];

export const FALLBACK_COLLEGES: College[] = [
  {
    id: "col-galgotias",
    name: "Galgotias University",
    city: "Greater Noida",
    state: "Uttar Pradesh",
    type: "Private",
    streams: ["Engineering & Technology", "Computer Applications", "Management & Commerce", "Law"],
    rating: 4.3,
    fee_range: "₹1.6 – 3.2 Lakh / year",
    description: "NAAC A+ campus near Delhi with strong placement support across engineering, management and law programmes.",
    featured: true,
  },
  {
    id: "col-amity-noida",
    name: "Amity University",
    city: "Noida",
    state: "Uttar Pradesh",
    type: "Private",
    streams: ["Engineering & Technology", "Management & Commerce", "Law", "Paramedical & Health"],
    rating: 4.5,
    fee_range: "₹2.8 – 4.5 Lakh / year",
    description: "One of India's most recognised private universities with 400+ programmes and a global alumni network.",
    featured: true,
  },
  {
    id: "col-sharda",
    name: "Sharda University",
    city: "Greater Noida",
    state: "Uttar Pradesh",
    type: "Private",
    streams: ["Engineering & Technology", "Management & Commerce", "Medical & Nursing", "Computer Applications"],
    rating: 4.2,
    fee_range: "₹1.8 – 3.6 Lakh / year",
    description: "Multi-disciplinary university with 270+ programmes, an on-campus hospital and students from 95+ countries.",
    featured: true,
  },
  {
    id: "col-srm-sonepat",
    name: "SRM University Delhi-NCR",
    city: "Sonepat",
    state: "Haryana",
    type: "Private",
    streams: ["Engineering & Technology", "Computer Applications", "Management & Commerce", "Pharmacy"],
    rating: 4.3,
    fee_range: "₹2 – 3.5 Lakh / year",
    description: "SRM's Delhi-NCR campus with modern labs, industry tie-ups and a dedicated placement cell.",
    featured: true,
  },
  {
    id: "col-lpu",
    name: "Lovely Professional University",
    city: "Phagwara",
    state: "Punjab",
    type: "Private",
    streams: ["Engineering & Technology", "Management & Commerce", "Computer Applications", "Arts & Media"],
    rating: 4.4,
    fee_range: "₹1.2 – 3.2 Lakh / year",
    description: "India's largest private university with 600+ programmes, top-class sports facilities and massive placement drives.",
    featured: true,
  },
  {
    id: "col-cu-mohali",
    name: "Chandigarh University",
    city: "Mohali",
    state: "Punjab",
    type: "Private",
    streams: ["Engineering & Technology", "Computer Applications", "Management & Commerce", "Pharmacy"],
    rating: 4.4,
    fee_range: "₹1.5 – 3 Lakh / year",
    description: "NAAC A+ university known for engineering excellence, record recruitment numbers and innovation labs.",
    featured: true,
  },
];
